# Generated by Django 3.2.7 on 2021-10-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='matchId',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
