# Generated by Django 3.2.7 on 2021-10-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LolApp', '0002_alter_match_matchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mode',
            field=models.TextField(default='NORMAL', max_length=50),
        ),
    ]
