# Generated by Django 3.2.7 on 2021-10-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LolApp', '0003_match_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='summonerId',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
