# Generated by Django 3.2.7 on 2021-10-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LolApp', '0004_alter_summoner_summonerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='champName',
            field=models.TextField(default='', max_length=200),
        ),
    ]
