# Generated by Django 3.2.7 on 2021-10-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LolApp', '0005_stats_champname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='totalDamage',
            field=models.IntegerField(default=0),
        ),
    ]
