# Generated by Django 3.2.7 on 2021-10-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LolApp', '0006_auto_20211005_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.TextField(default=0),
        ),
    ]
