# Generated by Django 3.2.7 on 2021-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LolApp', '0007_match_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='grade',
            field=models.FloatField(default=0),
        ),
    ]
