# Generated by Django 3.2.7 on 2021-10-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LolApp', '0010_gamechamp_gamemode_gameplatform_gamequeue_gameregion_gametype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameType',
        ),
        migrations.RemoveField(
            model_name='gamemode',
            name='id',
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='mode',
            field=models.TextField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamequeue',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
