# Generated by Django 3.2.7 on 2021-10-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LolApp', '0011_auto_20211007_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('mapId', models.IntegerField(primary_key=True, serialize=False)),
                ('mapName', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LolApp.gamequeue'),
        ),
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LolApp.gamemode'),
        ),
    ]
