# Generated by Django 3.2.7 on 2021-10-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LolApp', '0013_match_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='champName',
        ),
        migrations.AddField(
            model_name='stats',
            name='champ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LolApp.gamechamp'),
        ),
    ]
